---
title: "Experiences"
date: "`r Sys.Date()`"
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2  # Up to two depths of headings
    # theme: united  # Many options for theme
---

<style>
/* Adjust general text line spacing */
p {line-height: 1.75; font-size: 16px;}
h1 {font-size: 24px; text-align: center;} 
h2 {font-size: 22px; } 
/* Adjust line spacing in numbered or bulleted lists */
ul, ol {line-height: 1.5;}
</style>

## Graduate Research Assistant  
**School of Engineering Education, Purdue University**  
**Aug. 2024 – May 2025**  
- Perform psychometrics and analyze data from existing datasets  
- Develop, maintain, and refine adaptive testing and cognitive diagnostic algorithms  
- Conduct simulation studies to support research development  
- Coauthor conference and journal submissions  

---

## Volunteer Consultant  
**Psychometric Investigation Laboratory, Purdue University**  
**Dec. 2023 – Present**  
- Offer consultation on statistical methods, software support, research design, and data management/cleaning  
- Lead the ‘Using Machine Learning to Analyze Educational Data’ presentation series in the Research Methods & Statistics Workshop  

---

## Researcher  
**Suzhou’s Micro Monitoring and Micro Investigation Project, Education Psychology, ECNU**  
**Apr. 2022 – Present**  
- Collected and analyzed data from middle school classroom interactions  
- Investigated teacher-student interactions using video data from classroom teaching  

---

## Researcher  
**Optimizing the Teacher Training System of Clinical Pharmacist Project, Chinese Hospital Association & ECNU**  
**Jul. 2021 – Sep. 2021**  
- Analyzed factors influencing student satisfaction using ordinal logistic regression  
- Advocated for a diversified, process-based assessment system  

---

## Researcher  
**Suzhou’s Micro Monitoring and Micro Investigation Project, Education Psychology, ECNU**  
**Apr. 2021 – May 2022**  
- Investigated creativity and classroom creative climate of 4th and 8th grade students in Suzhou, China (4,833 students, 300 teachers, 48 schools)  
- Evaluated student creativity using the Rasch model and Wright map  
- Analyzed the relationship between student creativity and academic achievement using multilevel linear models and multivariable regression  

---

## Project Contributor  
**National Education Science “13th Five-Year Plan” 2020 National General Project, Education Psychology, ECNU**  
**Dec. 2020 – Present**  
- Explored the embedded assessment system oriented by key competencies  
- Conducted literature reviews and contributed to the theoretical framework  
- Acted as the main contact for project communications  

---

## Research Assistant  
**Surveys and Data Center, ECNU**  
**Sep. 2019 – Jun. 2020**  
- Investigated the lifestyle of urban residents in the Yangtze River Delta  
- Analyzed and cleaned large-scale survey data on the quality of life in Shanghai during the COVID-19 outbreak  
- Coauthored two journal papers  
- Debugged and updated the center’s official website  

---

## Research Assistant  
**Shanghai Science & Education Promotion Center**  
**Jul. 2018 – Dec. 2018**  
- Completed three evaluation reports commissioned by the Shanghai Science & Technology Museum, Shanghai Municipal Greening and City Appearance Administration, and Shanghai Statistics Bureau  
- Recruited volunteers for five popular science education activities  

---

## Researcher  
**Shanghai Innovation and Entrepreneurship Project, Statistics, ECNU**  
**Sep. 2016 – Sep. 2017**  
- Explored the city's perception and evaluation of international students in China  
- Interviewed 17 international students in person  
- Analyzed data using contingency tables  

---


## Awards, Honors, & Fellowships
<hr style="border: none; border-top: 3px solid black; width: 100%; margin-top: 1px; margin-bottom: 5px;" />

```{r, warning=FALSE,echo=FALSE, message=FALSE}
# Load necessary libraries
library(tibble)
library(knitr)  # Optional, for kable to display tables
library(kableExtra)

# Create a tribble
data <- tribble(
  ~Year, ~Content,
  "May 2025", "Psychometric Society Travel Award",
  "April 2025", "NCME Travel Award",
  "Mar. 2023", "Ross Fellowship",
  "Oct. 2022", "National Scholarship",
  "Oct. 2022", "Outstanding Student",
  "Oct. 2021", "Shu Qing Encouragement Scholarship",
  "Dec. 2020", "The Third Prize in the Contemporary Graduate Statistical Contest in Modeling",
  "July 2020", "The Second Prize in the COVID-19 Data Analysis Contest",
  "Nov. 2019", "The Third Prize for the Contemporary Undergraduate Statistical Contest in Modeling",
  "Nov. 2019", "Shanghai Popular Science Education Innovation Award",
  "Feb. 2019", "The Meritorious Winner in the Interdisciplinary Contest in Modeling (ICM)",
)

# Display the table with adjustable column widths, no full width, and text size adjustments
kable(data, "html", escape = FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
                full_width = F, 
                position = "left", 
                font_size = 18) %>%   # Adjust the overall font size of the table
  row_spec(0, bold = TRUE, font_size = 20) %>%  # Adjust font size and boldness for the header
  column_spec(1, width = "30%") %>%  # Adjust column width for Year
  column_spec(2, width = "70%")   # Adjust column width for Degree
```
