---
title: "Publications"
author: "Jing Huang"
date: "`r Sys.Date()`"
categories: ["R"]
output:
  html_document:
    toc: true
    toc_depth: 2  # Up to two depths of headings
    theme: united  # Many options for theme
---

<style>
/* Adjust general text line spacing */
p {line-height: 1.75; font-size: 18px;}
h1 {font-size: 24px; text-align: center;} 
h2 {font-size: 22px; } 
/* Adjust line spacing in numbered or bulleted lists */
ul, ol {line-height: 1.5;}
</style>

## Contents
- [Journal Articles](#journal-articles)
- [Conference Presentations](#conference-presentations)

# Journal Articles {#journal-articles}
1. Zheng, C., Liu, J., Li, Y., Xu, P., Zhang, B., Wei, R., ... & **Huang, J.** (2024). A 2PLM-RANK multidimensional forced-choice model and its fast estimation algorithm. *Behavior Research Methods*, 1-26.

2. Yang, X., **Huang, J.**, Chen, X., & Su, X. (2022). A Conceptual Analyses of Conceptual Understanding. *Exploring Education Development, 20*, 54-68. 

3. Li, Q., **Huang, J.**, & Xu, X. (2021). Relationship Between COVID-19 Infection Pneumonia and Traditional Chinese Medicinal Materials. *Chinese Journal of Medical Library and Information Science, 30*(01), 17-24. 

4. **Huang, J.**, & Xu, X. (2020). Research on the Influential Factors of Public Perception and Attitudes to the COVID-19: Based on the Citizen Survey of Shanghai. *Library Journal, 39*(12), 98-106. 

5. Xu, X., & **Huang, J.** (2020). Research on Executives’ Risk Perception and Behavior Choice to the COVID-19. *Library Journal, 39*(12), 117-127. 


# Conference Presentations {#conference-presentations}
1. **Huang, J.**, Yang, T., Yang, X. (2024, April). *Taking a “Whole” Perspective: Exploring the Influence of Individual and Environmental Factors on Creative Performance*. Round table presented at the annual meeting of the American Educational Research Association (AERA), Philadelphia, PA, USA.

2. **Huang, J.**, & Yang, X. (2022, April). *Model-based Approaches to Classifying Students into Competence-based Proficiency Levels*. Poster presented at the annual meeting of the American Educational Research Association (AERA), San Diego, CA, USA.



